### ISSUE TITLE
Get extension working consistently on PubMed

### ISSUE THREAD

**Issue by brandonStell** [PubPeerFoundation/PubPeerBrowserExtensions#14]
Many alerts are missing on Pubmed searches:
https://www.ncbi.nlm.nih.gov/pubmed?term=sarkar+fh+2014&cmd=DetailsSearch

To fix this we should add something like:

```
if url is PubMed:
  search for PMIDs (not for DOIs)
```
This will require exposing PMIDs in the PubPeer API (if that is not already done)

![image](https://user-images.githubusercontent.com/11091919/65314522-c8aeff80-db96-11e9-86e5-36de6479d649.png)

**Comment by brandonStell** [comment]
This will require the API to be queried by PMID as well as by DOI.

Something like this for example:
curl -d '{"pmids":["25333034"]}' -H "Content-Type: application/json;charset=UTF-8" -X POST https://pubpeer.com/v3/publications?devkey=Rogier

**Comment by XavRsl** [comment]
Sure. But how do you detect pubmed IDs on the client side? Pubmed IDs are
hard to identify...

Le jeu. 3 oct. 2019 à 12:42, Brandon Stell <notifications@github.com> a
écrit :

**Comment by brandonStell** [comment]
This change would only apply on the pubmed website.  It's possible to identify PMIDs on PubMed because they use the "PMID:" prefix.
