### ISSUE TITLE
PubPeer comments box overlaps first Google search result

### ISSUE THREAD

**Issue by HamidiMassinissa** [PubPeerFoundation/PubPeerBrowserExtensions#5]
* I encounterd this issue on Chrom(e|ium) as well as on Firefox, latest version.
* Bing search results with the same query seems ok and does not show the overlap on the first result.

Here is a screenshot illustrating the issue:
![pubpeer overlap issue](https://user-images.githubusercontent.com/8298445/37513629-e2e5ef20-2905-11e8-9381-180b0e00f0ca.png)

**Comment by XavRsl** [comment]
Hi,
Thank you for your report. Google changed the way they display the first result. One solution would be to ship a specific CSS rule with the PubPeer plugin, something like:
```css
#ires .f {
    height: inherit;
}
```
I'll keep you updated.

Thanks again.

Xavier
