### ISSUE TITLE
Add something (an icon) to deal with poorly placed DOIs

### ISSUE THREAD

**Issue by brandonStell** [PubPeerFoundation/PubPeerBrowserExtensions#9]
Sometimes DOIs are at the bottom of a page or in another inconvenient position which causes the html injected by the PubPeer plugin to be hidden from the user.

UnPaywall (https://chrome.google.com/webstore/detail/unpaywall/iplffkdpngmdjhlpjmppncnlhomiipha) has solved this by adding a small icon that floats on the right side of the page.  We could do something similar. 
We could add one for each commented DOI on the page.
Such a solution would also fix problems shown on the other issues.

**Comment by XavRsl** [comment]
Hi!
Came up with the same idea this morning! But I thought it would be a pain for pages like PubMed article list and such. Also, a lot of browser plugins are placing their content in the bottom right corner, and it sometimes gets in conflict with the site content itself. We should talk about it.

**Comment by brandonStell** [comment]
I think we should make an exception for PubMed.  When the URL is a PubMed URL we should search PMIDs (not DOIs) and use the current html injection.

For other pages that have long lists of PubPeer comments (very rare) we could show < 10 floating icons and when there are > 10 icons we show an (expandable) icon that says "There are over ten publications with PubPeer comments".

(however, institutional dashboards is the absolute priority for the moment)
